### ISSUE TITLE
Different DesktopIds of apps installed from Toolbox

### ISSUE THREAD

**Issue by dontfreakout** [swsnr/gnome-search-providers-jetbrains#54]
Hey Sebastian, it seems like JetBrains has made a change to the `DesktopId` naming convention for apps installed through the Toolbox. On my computer, the new naming format is as follows: 
```
.local/share/applications/jetbrains-idea-ce-d211586c-62fd-4cfe-adb1-9d90f48522af.desktop
.local/share/applications/jetbrains-phpstorm-ad84514d-ff59-4dd9-94f2-2309c20f8772.desktop
.local/share/applications/jetbrains-pycharm-ce-75af0a11-2bad-470d-9c3e-f2f8140e4b23.desktop
.local/share/applications/jetbrains-rustrover-13c360f9-655c-4f0e-b79b-3ead6b21d372.desktop
.local/share/applications/jetbrains-toolbox.desktop
.local/share/applications/jetbrains-writerside-06a26b58-5422-412d-bdd4-506f403864dd.desktop
```
I'm unsure if these guid suffixes are stable or not.

**Comment by swsnr** [comment]
I haven't noticed this yet.  I'll check next time I'm working w/ IDEA again.

Not sure if I can do anything about it any time soon, though.  I don't have a lot of time to work on this repo, and if those IDs are dynamic this probably means a larger refactoring of how we detect installed Jetbrains IDEs here.

Could you try to find out what these IDs are?  Perhaps ask Jetbrains support stuff?

**Comment by dontfreakout** [comment]
Yup, I'll definitely try to find out what these IDs are. 
No worries, I can build it for myself :wink:  

Once I know more, I will let you know and possibly create a pull request.

**Comment by swsnr** [comment]
@dontfreakout I just checked, but on my system I don't have these IDs in the desktop names 🤔

Is yours a fresh installation of toolbox?

**Comment by dontfreakout** [comment]
Yes, its fresh installation.

JetBrains just confirms that desktop file names now contain random UUIDs.
See discussion on [YouTrack](https://youtrack.jetbrains.com/issue/TBX-11262/Different-naming-scheme-of-.desktop-files-on-Linux)

**Comment by swsnr** [comment]
Thanks for clarifying.  I'll have to think about how to have this, and I'll perhaps add my two cents to that issue.

Will take a while though, just dint have much time for this.

**Comment by dontfreakout** [comment]
Hi @swsnr, I just want to let you know that JetBrains will hopefully update Toolbox with a backward-compatible naming scheme. So no changes on your side will probably be necessary :slightly_smiling_face:

**Comment by swsnr** [comment]
@dontfreakout Since it's been two months, what's the status here?  Can we close this issue?

**Comment by swsnr** [comment]
@dontfreakout I'm closing this issue, because to me it's not actionable currently, as I'm not affected by this.

Feel free to re-open or make another follow-up ticket if there's any specific change to be done here.
